### ISSUE TITLE
Add test for getStreams with multiple chunks

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/xenon-grpc#11]
Use multiple messages to `cat` interactive job and fetch responses after each request.

**Comment by sverhoeven** [comment]
See f2da2e1fcf823d2593359840d93e72c4d74a144e

**Comment by sverhoeven** [comment]
Added test in https://github.com/NLeSC/xenon-grpc/blob/get-streams-cat-test/src/test/java/nl/esciencecenter/xenon/grpc/jobs/LocalJobsStreamsTest.java, but if fails to recieve the first message from the server (at line [#122](https://github.com/NLeSC/xenon-grpc/blob/get-streams-cat-test/src/test/java/nl/esciencecenter/xenon/grpc/jobs/LocalJobsStreamsTest.java#L122)).

The test is modeled after the [example of grpc java](https://github.com/grpc/grpc-java/blob/master/examples/src/test/java/io/grpc/examples/routeguide/RouteGuideServerTest.java#L196-L264)

Even if the timeout is increased the StreamForwarder threads don't write.

**Comment by atzeus** [comment]
Fixed by d015ffa5904e535c6acd09d2b5d0aa25c885b223

**Comment by sverhoeven** [comment]
It works for you but sometimes it doesn't work for me. It stalls midway somewhere.

Created https://github.com/NLeSC/xenon-grpc/tree/debug-getstreams-test branch to find out where it stalls.
