### ISSUE TITLE
Interactive jobs IO blocking (in PyXenon)

### ISSUE THREAD

**Issue by jhidding** [NLeSC/xenon-grpc#13]
Streaming IO from interactive jobs is locking (what we feared would happen). The example I'm trying to run is here: https://github.com/NLeSC/pyxenon/blob/grpc/examples/interactive.py

Other than the blocking IO issue, streams seem to work Ok.

**Comment by sverhoeven** [comment]
Solved with https://github.com/NLeSC/xenon-grpc/issues/11, could you try again?

**Comment by jhidding** [comment]
Yes! it works :)
