### ISSUE TITLE
Identify job-id in JobOutputStreams

### ISSUE THREAD

**Issue by jhidding** [NLeSC/xenon-grpc#18]
As I see it, there currently is no way to see which job is giving output. Or is this fixed by sending an empty message to the JobInputStream?

**Comment by sverhoeven** [comment]
The client asked for a JobOutputStreams using the getStreams rpc method. 
The getStream method requires a job object as input, any yields on the JobOutputStreams will be of that job.
So the client should keep track which JobOutputStreams belongs to which job.
