### ISSUE TITLE
Change JobWithTimeout to contain instance of job

### ISSUE THREAD

**Issue by jhidding** [NLeSC/xenon-grpc#23]
This change would better fit the underlying OOP design.

**Comment by sverhoeven** [comment]
```python
scheduler.wait_until_done(job=job, timeout=1000)
```
of OOP
```python
job = scheduler.submit_batch_job(...)
job.wait_until_done(42)
```

**Comment by jspaaks** [comment]
At some point I had a discussion with Jason / @jmaassen  about the OOP'ness (of Java Xenon) where this point came up. Our conclusion back then was that it makes more sense to limit OOPness to some toplevel objects. 

In other words 

- ``scheduler.waituntildone`` yes
- ``job.waituntildone`` no

**Comment by jhidding** [comment]
Ok, we'll keep it like it is.
